name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.12
      uses: actions/setup-java@v1
      with:
        java-version: 1.12
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: Warchant/setup-sonar-scanner@v1
    - name: sonar-scanner
      with:
          version: 4.2.0.1873
