name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.12
      uses: actions/setup-java@v1
      with:
        java-version: 1.12
    - name: Build with Maven
      uses: sonarsource/sonarcloud-github-action@master
      run: mvn sonar:sonar  -Dsonar.projectKey=decipherDev_hibernate-starter -Dsonar.organization=decipherDev -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=fc5eb02dba58ef8e8c16fda879444e2e534eed52 --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
